//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOS2Randomizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DOS2Randomizer.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some spell have dependencies that could not be matched against their image file names:.
        /// </summary>
        internal static string CorruptDependencies {
            get {
                return ResourceManager.GetString("CorruptDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file &apos;&apos;{0}&apos;.
        /// </summary>
        internal static string FileOpenFailed {
            get {
                return ResourceManager.GetString("FileOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered two images files with the same name (&quot;{0}&quot; and &quot;{1}&quot;)..
        /// </summary>
        internal static string ImageNamesNotUnique {
            get {
                return ResourceManager.GetString("ImageNamesNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import config file. Did you import to correct config file (Spell vs Match config)?.
        /// </summary>
        internal static string ImportConfigFailed {
            get {
                return ResourceManager.GetString("ImportConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid values in config: .
        /// </summary>
        internal static string InvalidConfigValues {
            get {
                return ResourceManager.GetString("InvalidConfigValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Spells config. Could not find icon for the following spells:.
        /// </summary>
        internal static string InvalidSpellConfig {
            get {
                return ResourceManager.GetString("InvalidSpellConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read config file &apos;{0}&apos;.
        /// </summary>
        internal static string JsonParseFailed {
            get {
                return ResourceManager.GetString("JsonParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json error while serializing: .
        /// </summary>
        internal static string JsonSerializeFailed {
            get {
                return ResourceManager.GetString("JsonSerializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of players reached..
        /// </summary>
        internal static string MaxNumPlayers {
            get {
                return ResourceManager.GetString("MaxNumPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some spells could not be matched by their image file names:.
        /// </summary>
        internal static string MismatchedSpells {
            get {
                return ResourceManager.GetString("MismatchedSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spells are loaded..
        /// </summary>
        internal static string NoSpells {
            get {
                return ResourceManager.GetString("NoSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving config. IO error: .
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
    }
}
